### ISSUE TITLE
Missed SCGs when using DIAMOND

### ISSUE THREAD

**Issue by dparks1134** [cmks/DAS_Tool#10]
Hello,

I have run into an issue using Das Tool with using DIAMOND to identify SCG. It would appear that many SCGs can go unidentified. I've determined this by using a small data sets where the results differ substantially from using a larger set of bins (and from the USEARCH results and estimates with CheckM). For the test case, I've truncated the contigs file to only those in the few test bins I am considering which substantially changes the SCGs identified with DIAMOND relative to using the complete contigs file. Perhaps the number of hits returned by DIAMOND needs to be increased. The default (strangely) is to return only the top 25 hits!

Have you run across this issue? I am using DIAMOND v0.9.8.

Regards,
Donovan

**Comment by dparks1134** [comment]
If it helps, I have verified that the identified SCGs in the *.bacteria.scg differ for a given contig depending on the other contigs that are in the query contig file.

**Comment by AJProbst** [comment]
Dear Donovan,
I've tested the single copy gene prediction with diamond v0.8.37 and diamond v0.9.9 and was unable to reproduce the error on two independent systems (usearch finds the exact same amount of SCGs as diamond v0.9.9).
Would you mind providing an example?
Thanks, Alex

**Comment by dparks1134** [comment]
Thanks for the quick reply Alex. I'll do some more digging on my end.

**Comment by dparks1134** [comment]
I do seem to have a real issue. I am using BLASTp v2.6.0 and DIAMOND v0.9.9. I've been applying these to the gold standard assembly of the high complexity simulated community that is part of CAMI (CAMI_high). You can download this at https://data.cami-challenge.org/participate or directly at https://s3-eu-west-1.amazonaws.com/cami-data-eu/CAMI_high/CAMI_high_GoldStandardAssembly.fasta.gz. The BLAST and DIAMOND results are substantially different. For example, on contig "RH|P|C27300" the BLAST results give 35 bacterial SCG while the DIAMOND results give only 3. Based on secondary information (CheckM estimates), I highly suspect the BLAST results are correct and something is wrong with DIAMOND. 

These results are for Das Tool source code download yesterday.

**Comment by AJProbst** [comment]
Hi Donovan,
I've run Usearch and Diamond on the Cami dataset and is definitely a difference between the number of SCGs detected by Usearch and Diamond.
Regarding the example of scaffold RH|P|C27300, Usearch finds 35 SCGs and Diamond does really find only 3 - although we used identical cutoffs.  We optimized the Script for Usearch and will further look into optimizing for Diamond and also Blastp in the near future. We strongly recommend to use DAS Tool with Usearch for now.
Nevertheless, I was unable to reproduce the reported error that Diamond only detects 25 SCGs in total.
Thanks so much for reporting this,
Alex

**Comment by dparks1134** [comment]
Hey Alex,
Glad this has been useful. I believe the issue is that by default DIAMOND only reports the top 25 hits to each query gene. I think this is truncating the set of valid SCG hits reported by DIAMOND which is ultimately resulting in the observed discrepancy.  This is just a gut feeling, but the default behaviour of DIAMOND is pretty strange (i.e., why not the top 500 hits meeting the E-value criteria in order to be a drop in replacement with BLASTp).
Cheers,
Donovan

**Comment by AJProbst** [comment]
Hi Donovan,
good thought and it would make a lot of sense because we first select candidates using a low stringency blast and then blast those candidates against the actual database (reverse blast for improved confidence). The initial selection with diamond could truncate the actual candidates that we then search for in the dataset.
I'm not sure how we can solve this issue for now, so I would recommend using blastp or usearch until we have come up with a solution for that. So I hope that you can use DAS Tool for now with blastp at least (Usearch requires a license for huge datasets unfortunately). 
Thanks so much for finding and reporting this,
Alex

**Comment by cmks** [comment]
Hi Donovan,
Hi Alex,

Thanks a lot for reporting this bug and for investigating. I will remove the DIAMOND support for now until we know exactly what causes this strange behavior.
Meanwhile, I also recommend using usearch or blast. The 32 bit version of usearch is free but limited to single core usage. The database limit (due to 32 bit) of this version is sufficient for most metagenomics datasets.

Cheers and thanks again,
Christian

**Comment by nick-youngblut** [comment]
I believe DIAMOND has been updated since June. Any idea if the newest version of DIAMOND will work for DAS-tool? Thanks!

**Comment by smdabdoub** [comment]
Vsearch was built with the intention of creating an open source USEARCH, replicating its functionality and even command-line parameters, but without the 32-bit limitation. It should be a drop-in replacement (or pretty close).

**Comment by nick-youngblut** [comment]
Thanks for the feedback! Could I just find-and-replace usearch for vsearch, or would I have to modify the code a bit more than that?

**Comment by AJProbst** [comment]
I don't think we can use vsearch. I've explored the possibility of using it for the code but I think it doesn't provide a bitscore or e-value if I remember correctly.

**Comment by smdabdoub** [comment]
They provide a --blast6out option (with evalue and bitscore fields) intended for compatibility with usearch: https://github.com/torognes/vsearch/issues/179#issuecomment-217887395.

**Comment by cmks** [comment]
The output format compatibility to usearch is definitely very useful. However, as far as I can see vsearch still does not support amino acid sequences (https://github.com/torognes/vsearch/issues/42).

**Comment by smdabdoub** [comment]
Ahh, I didn't realize they still didn't have support for AA alignment.

Getting back to DIAMOND, and to respond to https://github.com/cmks/DAS_Tool/issues/10#issuecomment-312073279, did anyone take a look at the --max-target-seqs output option? As was noted, the default reported alignments is limited to 25, but setting that option to 0 will make it report all found alignments.

**Comment by cmks** [comment]
The integration of DIAMOND is still on our schedule. We need to run some testing and benchmarking first in order to find out how well the new version performs on single copy gene detection.

**Comment by cmks** [comment]
We tested and included DIAMOND as single copy gene search again. It can be used with the setting `--search_engine diamond`.

Christian
