### ISSUE TITLE
*.scg not created in v1.1.0

### ISSUE THREAD

**Issue by gerners** [cmks/DAS_Tool#11]
Hello,

I received an error about missing *.faa.scg files after switching to the new version 1.1.0. Terminal Output is the following:

```
dastool -i /workdata/dastool/concoct_contigs2bin.tsv,/workdata/dastool/maxbin_contigs2bin.tsv,/workdata/dastool/metabat_contigs2bin.tsv -l concoct,maxbin,metabat -c /contigs/sacramento_1A.contigs.fa -o /workdata/dastool-1.1.0/sacramento_1A --threads 30 --search_engine blast --write_bins
predicting genes using prodigal
identifying single copy genes using blast
mv: cannot stat '/workdata/dastool-1.1.0/sacramento_1A_proteins.faa.scg': No such file or directory
mv: cannot stat '/workdata/dastool-1.1.0/sacramento_1A_proteins.faa.scg': No such file or directory
rm: cannot remove '/workdata/dastool-1.1.0/sacramento_1A_proteins.faa.findSCG.b6': No such file or directory
rm: cannot remove '/workdata/dastool-1.1.0/sacramento_1A_proteins.faa.scg.candidates.faa': No such file or directory
rm: cannot remove '/workdata/dastool-1.1.0/sacramento_1A_proteins.faa.all.b6': No such file or directory
running DAS Tool with 30 threads
Execution halted
```
No difference if run with usearch or blast. Same command with version 1.0.0 using diamond ran through without any error e.g.

```
dastool.sh -i /workdata/dastool/concoct_contigs2bin.tsv,/workdata/dastool/maxbin_contigs2bin.tsv,/workdata/dastool/metabat_contigs2bin.tsv -l concoct,maxbin,metabat -c /contigs/sacramento_1A.contigs.fa -o /workdata/dastool-1.1.0/sacramento_1A --threads 30 --search_engine diamond --write_bins                                                                           
predicting genes using prodigal
identifying single copy genes using diamond
running DAS Tool with 30 threads
evaluating bin-sets
starting bin selection from  12  bins
||||||
extracting bins to /workdata/dastool-1.1.0/sacramento_1A_DASTool_bins
```

Looking into the output directory, only the sequence length file and the prodigal *.faa are created but it seems the *.scg files observed in the output from v1.0.0 are missing as the error says as well. Might be related to the already reported issue #5 except the file sacramento_1A_proteins.faa is created and found in my case.

The exact versions I am using are commit 97990da for v1.0.0 and the current commit d60329f for v1.1.0.
I put dastool into a Docker container, the only difference between the two containers is a more current R version (R 3.4.0 for dastool v1.0.0 and R 3.4.1 for dastool v1.1.0), all the other dependencies remained the same. Do you know where the error might come from?

Thanks,
Samuel

**Comment by cmks** [comment]
Hi Samuel,

Thanks for using DAS Tool!
One possibility why you get this error message is that you didn't extract the single copy gene database in your DAS Tool installation directory. Can you please check if that's the case?

You should have a folder named `db` in the DAS Tool installation directory containing the files:
```arc.all.faa
bac.all.faa
arc.scg.faa
arc.scg.lookup
bac.scg.faa
bac.scg.lookup
```

If you're missing the folder simply cd into the DAS Tool installation and hit:
`unzip db.zip`

Let me know if that solves the problem. Anyway, I'll ad a more specific error message to take this case into account and to avoid confusion in the future. Thanks for reporting!

Cheers,
Christian

**Comment by gerners** [comment]
Hi Christian,

Thanks for the quick reply! The `db ` folder is correctly unzipped and present in the current version, so that should not be the origin of the problem in my case. 
Also a colleague of mine has a similar error report independent of me, in fact the reason why I looked into my install again. I'll ask if the `db` folder is correctly extracted with his install as well.

If you want to take a look, I made both Docker images public under [https://hub.docker.com/r/gerners/dastool/](https://hub.docker.com/r/gerners/dastool/), the image with v1.1.0 is tagged as latest and 1.1.0 while the image with v1.0.0 is tagged with 1.0. I will run some more samples to see if the error is persistent and can give you example data if need be.

Cheers,
Samuel

**Comment by cmks** [comment]
Hi Samuel,
I can't reproduce the error you are getting. I have tested my local installation and your Docker container on the small sample dataset (sample_data folder in install dir) and on a larger dataset of my own. In both cases DAS Tool terminates successfully without error message:
```
$ docker pull gerners/dastool

$ docker run -it -v ~/Projects/DAS_Tool/sample_data:/sample_data gerners/dastool -i /sample_data/sample.human.gut_concoct_scaffolds2bin.tsv,/sample_data/sample.human.gut_maxbin2_scaffolds2bin.tsv,/sample_data/sample.human.gut_metabat_scaffolds2bin.tsv,/sample_data/sample.human.gut_tetraESOM_scaffolds2bin.tsv -l concoct,maxbin,metabat,tetraESOM -c /sample_data/sample.human.gut_contigs.fa -o /sample_data/DASToolRun1 --search_engine blast

predicting genes using prodigal
identifying single copy genes using blast
running DAS Tool with 1 threads
evaluating bin-sets
starting bin selection from  20  bins
|||||||||||||||
```

Can you please send me the list of files that DAS Tool generates before it crashes? Also, can you try to execute the SCG-finder script in the DAS Tool install dir manually:
```
$ ruby DAS_Tool_dir/src/scg_blank_blast.rb blast /workdata/dastool-1.1.0/sacramento_1A_proteins.faa DAS_Tool_dir/db/bac.all.faa DAS_Tool_dir/db/bac.scg.faa DAS_Tool_dir/db/bac.scg.lookup 1
```

Thanks,
Christian

**Comment by gerners** [comment]
Hi Christian,

Thanks a lot, I believe I found the error, in the end it was a permission issue. The sample data worked fine with both container versions, when I tried the ruby script by itself, I got the following error messages

```
ruby /opt/DAS_Tool/src/scg_blank_blast.rb blast /workdata/dastool-1.1.0/sacramento_1A_proteins.faa /opt/DAS_Tool/db/bac.all.faa /opt/DAS_Tool/db/bac.scg.faa /opt/DAS_Tool/db/bac.scg.lookup 1
database name of all proteins is /opt/DAS_Tool/db/bac.all.faa
database name of SCGs is /opt/DAS_Tool/db/bac.scg.faa
database lookup is /opt/DAS_Tool/db/bac.scg.lookup
Error: NCBI C++ Exception:
    T0 "/home/coremake/release_build/build/PrepareRelease_Linux64-Centos_JSID_01_350334_130.14.22.10_9008__PrepareRelease_Linux64-Centos_1481139955/c++/compilers/unix/../../src/objtools/blast/seqdb_writer/build_db.cpp", line 1021: Error: BLASTDB::ncbi::s_CreateDirectories() - You do not have write permissions on 'db'
```

The two files which were created before the crash are the following:
```
sacramento_1A.seqlength
sacramento_1A_proteins.faa
```

The reason why you could not reproduce the error is that I usually run my docker containers with  the options **-u $(id -u):$(id -g)**, thereby running it with the current user ID within the container, while the files in the container are owned by root. I believe this will also be the issue with a friend of mine having the same issue having the installation on a cluster, where the installdirectory likely has no write permission for standard users.
I assume no write actions were needed for the db directory in the install dir with diamond in v1.0.0 contrary to blast and usearch in v1.1.0.

Rerunning everything with root in docker was successful with my data.

Probably you can change that behaviour so that no write permission is needed in the install directory?

**Comment by snayfach** [comment]
I'm getting this same error using v1.1

**Comment by cmks** [comment]
Hi Samuel,
Thanks for your feedback! I implemented some changes so that the blast script is not writing into the install directory any more.
Cheers,
Christian

**Comment by liucong2016** [comment]
sorry, I have a question. `ubuntu@ip-172-31-11-17:~/LC$ ./usearch11 -sintax ~/LC/18s-A-otus-nochimera.fa ‐db silva_18s_v123.fa ‐strand both ‐tabbedout 18s‐A‐otu‐tax.txt ‐sintax_cutoff 0.5`
-bash: ./usearch11 -sintax: No such file or directory

I do not know what is wrong??
