### ISSUE TITLE
option to specify location of database

### ISSUE THREAD

**Issue by nick-youngblut** [cmks/DAS_Tool#14]
Currently, `DAS_Tool` has no option for specifying the directory of the DAS_Tool database. If possible, I'd like to keep the database separate from the executable for version control reasons. I've modified `DAS_Tool` to find the database in another directory, but it would be great if this was an option in `DAS_Tool`

**Comment by cmks** [comment]
Hi Nick,

Thanks for your suggestion and for using DAS Tool. I will add an option to define the DB location as soon as I have some time.

Christian

**Comment by cmks** [comment]
It is now possible to specify the database directory using the flag `--db_directory`.

Christian
