### ISSUE TITLE
empty scg-files created, script exits prematurely

### ISSUE THREAD

**Issue by jvollme** [cmks/DAS_Tool#15]
I am using DAS_tool 1.1.0 (the newest commit on github). However, DAS_tool keeps aborting before finishing with my data. The scg files created by the "ruby" blast step are empty.

 I reran the "ruby" step without redirection of stderr & stdout to see what might be going on, and i found these lines (the same happends for bacterial and archeal scg detection):

```
[...]
sh: pullseq: Kommando nicht gefunden.
verifying selected SCGs...
Warning: [blastp] Query is Empty!
starting annotations of single copy cogs...
successfully finished
```

So apparently the ruby script could not find pullseq, although it is clearly installed in my environment.
Could the problem maybe be that the ruby script has a shebang explicetly referering to ```/usr/bin/ruby``` and not to my conda environments ruby (although since it was called from within my environment, I think it should still detect tools in my environments PATH, right)?
Maybe the shebang should be changed to ```#!/usr/bin/env ruby```?

Edit:
Tried changing the shebang locally... Didn't help: pullseq is still not recognized!
does ruby somehow not recognize my environments PATH? Why?

**Comment by cmks** [comment]
It looks like your environment variables are not visible in ruby. However, DAS_Tool can find pullseq, otherwise it would terminate with an error message right away.

Unfortunately, I can't reproduce your ruby problem.

**Comment by jvollme** [comment]
Turned out correcting the shebang fixed the problem after all. It only seemed that the rerun after initially fixinf the shebang also failed, simply because I did not notice that DAS-tool skips the "ruby" step if it thinks the output files exist already.
so:
- changing the shebang of the ruby-scripts to the more generally applicable "#!/usr/bin/env ruby" 
- deleting any remaining intermediate results from previous runs
fixed the problem

I am pretty sure you could not reproduce the ruby problem simply because the current shebang is applicable for **you** on **your** system (I guess you have the correct ruby version globally installed and added to your PATH).

Try a system with an global installation of an incorrect (old) version of ruby where all dependencies (including the correct ruby) have been installed in a conda environment using [bioconda](https://bioconda.github.io/). That should reproduce the problem (and also be representative for any users having to work on public servers provided by their Institutes)

**Comment by cmks** [comment]
This problem has been solved. Thanks to @SilasK for pull request #25.
