### ISSUE TITLE
cannot run command “./DAS_Tool.sh"

### ISSUE THREAD

**Issue by zhangws119** [cmks/DAS_Tool#2]
Hi, it is a great software where I know from the paper. But, I cannot run the command "./DAS_Tool.sh" after I complete the INSTALL. 

"bash:./DAS_Tool.sh:Permission denied"  --------When I run the command.

Could you tell me how to run the DAS_tool normally?

Many thanks!

**Comment by cmks** [comment]
Hi,

Thanks for downloading DAS Tool! 
It seems like the DAS_Tool script is not executable on your system. Try the following to add the necessary permissions:

chmod u+x ./DAS_Tool.sh

...and then try to run it again:

./DAS_Tool.sh -h

Thanks,
Christian
