### ISSUE TITLE
Can't find the .zip file in installation instructions

### ISSUE THREAD

**Issue by pyilmaz** [cmks/DAS_Tool#21]
Hello,
I can't seem to locate the .zip file mentioned in the installation:

Download and extract DASTool.zip archive:
unzip DAS_Tool.v1.1.zip
cd ./DAS_Tool.v1.1

Incidentally, I also can't install the tool. Thanks for your help!

**Comment by cmks** [comment]
Hi,
You can download the latest stable release under "releases" in clicking on "[Source code (zip)](https://github.com/cmks/DAS_Tool/archive/1.1.0.zip)" of DAS Tool 1.1.0.

Alternatively, you can get the latest snapshot in executing `git clone https://github.com/cmks/DAS_Tool.git` in your terminal.

Christian
