### ISSUE TITLE
sub.contigs and contigs

### ISSUE THREAD

**Issue by Handymanalan** [cmks/DAS_Tool#22]
Hi Christian,

I would like to ask what's the difference between sub_contigs and contigs, which are the output of DAS_Tool?

Cheers and many thanks

Alan

**Comment by cmks** [comment]
Hi Alan,

I'm not exactly sure what you mean by sub_contigs.
Anyway, DAS Tool attaches a '_sub' postfix to bins of which contigs were removed during the selection process. This will happen if two (or more) bins from different predictions have common contigs and two (or more) of these bins are selected into the final bin set. Here's an example with two binning predictions where one contig is part of two different bins (contig_03 in predictionA_bin01 and predictionB_bin02):

Prediction A:
```
contig_01	predictionA_bin01
contig_02	predictionA_bin01
contig_03	predictionA_bin01
contig_04	predictionA_bin02
contig_05	predictionA_bin02
contig_06	predictionA_bin03
```

Prediction B:
```
contig_01	predictionB_bin01
contig_02	predictionB_bin01
contig_03	predictionB_bin02
contig_04	predictionB_bin02
contig_05	predictionB_bin02
contig_06	predictionB_bin02
```

If DAS Tool selects predictionA_bin01 and predictionB_bin02 the result will look like:
```
contig_01	predictionA_bin01
contig_02	predictionA_bin01
contig_03	predictionA_bin01
contig_04	predictionB_bin02_sub
contig_05	predictionB_bin02_sub
contig_06	predictionB_bin02_sub
```

I hope this answers your question.

Cheers,
Christian

**Comment by Handymanalan** [comment]
Yeah that does!

Thanks!

Alan
