### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SilasK** [cmks/DAS_Tool#23]
Hello I'd like to make a [bioconda recipie](https://github.com/bioconda/bioconda-recipes/pull/10007 ) of your package, to make it easier to install and integrate into workflows. 

Because you haven't specified any license,  I wanted to clarify if the package is freely available at least when used with blast or diamond. (usearch is not open-source).

Kind regards
Silas

**Comment by cmks** [comment]
Hi Silias,

That's great, I appreciate your effort!
DAS Tool is freely available and licensed under the Berkeley Software Distribution (BSD) license (see [license.txt](https://github.com/cmks/DAS_Tool/blob/master/license.txt)). All libraries and dependencies (except usearch) are also available under open source licenses. 
Let me know if you need more information.

Cheers,
Christian
