### ISSUE TITLE
multiple samples

### ISSUE THREAD

**Issue by SilasK** [cmks/DAS_Tool#24]
Hello, 

Is it possible to combine bins from multiple samples assembled separately? 
It is not clear in the paper how you did that in the paper. Concoct and metabat use differential abundance of contigs in different samples, which normally requires co-assembly of the samples. But you state in the methods that all samples are assembled separately, what to my experience also gives better contigs. Could you explain?

Kind regards
Silas

**Comment by cmks** [comment]
Hi Silas,

You can't combine bins from multiple assemblies using DAS Tool. In the paper, we assembled all samples separately and mapped reads from all samples to the assemblies to get the differential abundance information. In doing so we end up with (# of samples)^2 mappings. The mappings for each assembly are then used for binning.
To de-replicate genome bins between samples afterwards I can recommend the tool dRep (https://github.com/MrOlm/drep and https://www.nature.com/articles/ismej2017126).

Christian

**Comment by SilasK** [comment]
Thank you, 

I stumbled over it. However, Derep only choses the best genome, but doesn’t improve them by dereliction of genomes.  Any way I will give it a try.

**Comment by SilasK** [comment]
Thanks for your comment
