### ISSUE TITLE
DAS Tool decreases quantity and quality of bins compared to maxbin

### ISSUE THREAD

**Issue by SilasK** [cmks/DAS_Tool#26]
How can this happen?

![f32_dastool_hqbins](https://user-images.githubusercontent.com/7523034/43462668-019e38fe-94d7-11e8-9541-a888dd2868b3.png)

![f32_dastool_scores](https://user-images.githubusercontent.com/7523034/43462702-1ab37674-94d7-11e8-888f-c3182a8fe615.png)

**Comment by cmks** [comment]
Interesting, can you re-run DAS Tool on your data with the flag `--debug 1` and with an empty output directory? If you send me the output files to `csieber@lbl.gov`, I can take a look at what's going on. Please send me all output files except the `*_proteins.faa. If you want you can also include your input scaffold2bin files - the assembly is not necessary.

Thanks,
Christian

**Comment by SilasK** [comment]
I will rerun it. Does it matter if the proteins are predicted independently
with prodigal 2.6 or not?

**Comment by cmks** [comment]
If you use prodigal 2.6.3 you can predict proteins independently and pass them via the `--proteins` option.

**Comment by sergio05031** [comment]
Hello, 

I am observing similar patterns in my data:

![image](https://user-images.githubusercontent.com/36368696/43998402-63f0e87e-9dcb-11e8-9592-16eba7ac2dcb.png)
![image](https://user-images.githubusercontent.com/36368696/43998407-7aa1c692-9dcb-11e8-8ac3-04295c736a66.png)

Thank you for your help,

**Comment by sergio05031** [comment]
I have found the source of the error in my case.

Bin IDs for every binner were the same. Even though DASTool reports that and apparently tries to fix it (WARNING: non-unique bin-IDs found, creating unique bin-IDs), something is wrong.
After I made the bin IDs unique, by appending the prefix of the binner to the bin ID in each case, the problem was solved.

![image](https://user-images.githubusercontent.com/36368696/44002539-b0e7f6aa-9e1a-11e8-8083-e57cb1554399.png)

![image](https://user-images.githubusercontent.com/36368696/44002542-bd62903e-9e1a-11e8-981a-a2ebf722171e.png)

**Comment by SilasK** [comment]
Exactly, I think DAS_Tool preppebds the name of the scaffold2bin fles to
the bin id.

Were your scaffold2bin file names different or not?

**Comment by SilasK** [comment]
@sergio05031 I'm quite surprised by your results: In your results, maxbin is the wors binner, whereas in my experience as well as in the DAS paper it was always the best. 

I would be interested in understanding why your metabat and concoct results are so much better. Do you use co-assembly?

**Comment by sergio05031** [comment]
Yes, it is a weird pattern. And you are right, I used co-assembly (sometime of geographically distant, but similar, environments). Do you think that could be the cause?

**Comment by SilasK** [comment]
I can imagine. Concoct and metabat both use co-abundance patterns, which work well for co-assemblies and many samples. In my test and in the DAS paper we applied the binner on single-sample-assemblies. It seems that maxbin performs better in this case.

**Comment by SilasK** [comment]
So, renaming the scaffold2bin files solved the problem. DAS_Tool takes the filenames as prefix to make the bins unique. 
@cmks I suggest checking if this prefixes are unique and throw an error if not. Or using the labels as prefix to make the bins unique.
