### ISSUE TITLE
Might it be that DasTool get rid of 16S sequences

### ISSUE THREAD

**Issue by SilasK** [cmks/DAS_Tool#28]
Hello, Inpredicted the 16S from the bins produced by DasTool from (concoct, metavat and maxbin results). I'm surprised that there are soo litle 16S sequences in bins (most are in the unbinmed fraction).

I assume that DASTool doesn't care about contigs eith rRNA genes, as thery are not single copy genes. But could this result that they are just left aside?

**Comment by cmks** [comment]
Dealing with 16S genes is in general a tough problem for binners (and also for assemblers). The conserved sequence of the 16S gene influences k-mer and abundance profiles of contigs and may cause that contigs with 16S gene don't get clustered with other contigs from the same organism. This is especially a problem if the 16S containing contigs are short and only contain the 16S gene.

You assumed correctly that DAS Tool does not evaluate the presence of 16S genes in bins and it is also not excluding them actively. The reason why you're observing many unbinned 16S contigs is most likely related to the difficulty of binners binning these contigs.

**Comment by SilasK** [comment]
Thank you for the explanation
