### ISSUE TITLE
Usage， -i  "scaffolds2bin.tsv"

### ISSUE THREAD

**Issue by zhangws119** [cmks/DAS_Tool#3]
Hi, thanks for your reply about the installation. But now I have a new problem about the Usage "-i"

In the Examples, I saw some .tsv files, and I cannot understand the description about "-i --BINs"

## Bins [--bins, -i]: Tab separated files of scaffold-IDs and bin-IDs. Scaffold to bin file example:
Scaffold_1	bin.01
Scaffold_8	bin.01
Scaffold_42	bin.02
Scaffold_49	bin.03

If I have hundreds of bins from one scaffold, how I separated them? Like ?

Scaffold_1      *_Cluster.1.fa
Scaffold_1      *_Cluster.2.fa
Scaffold_1      *_Cluster.3.fa

Could you tell me how to make the "sacffolds2bin.tsv" files?

Many  Many thanks! 

I'm looking forward your reply!

**Comment by cmks** [comment]
Hi,

I’m not sure if I understand your question correctly. For each binning prediction a scaffold is assigned to exactly one bin. However, if you run three different binning methods (e.g. method A, B and C) on the same assembly probably each of the binning methods will assign a certain scaffold to a different bin. To prevent mixing between methods, each result is stored in its own scaffolds2bin file e.g.:

methodA_scaffolds2bin.tsv:
Scaffold_1	methodA_Bin01
Scaffold_9	methodA_Bin01
Scaffold_2	methodA_Bin02
...

methodB_scaffolds2bin.tsv:
Scaffold_1	methodB_Bin05
Scaffold_9	methodB_Bin02
Scaffold_2	methodB_Bin03
...

methodC_scaffolds2bin.tsv:
Scaffold_1	methodC_Bin07
Scaffold_9	methodC_Bin03
Scaffold_2	methodC_Bin42
…

In this example method A assigns Scaffold_1 and Scaffold_9 into the same bin. Method B and C assign it to completely different bins.

There are some binning tools that don’t provide results as scaffolds2bin table but only as fasta files. In this case usually one fasta file corresponds to one bin. I uploaded a script on github (src/Fasta_to_Scaffolds2Bin.sh) that converts bins in fasta format to a scaffolds2bin table.

I hope I could answer your question.

Regards,
Christian

**Comment by zhangws119** [comment]
@cmks  

Hi, thanks very much for your script, it is great to make "scaffolds2bins.tsv" files.

However, It show me something wrong when I run the example_1 Usage. Like this,

**# "predicting genes using prodigal
identifying single copy genes using /usr/local/bin/usearch9.2.64_i86linux32
mv: cannot stat `sample_output/DASToolRun1_proteins.faa.scg': No such file or directory
mv: cannot stat `sample_output/DASToolRun1_proteins.faa.scg': No such file or directory
rm: cannot remove `sample_output/DASToolRun1_proteins.faa.findSCG.b6': No such file or directory
rm: cannot remove `sample_output/DASToolRun1_proteins.faa.scg.candidates.faa': No such file or directory
rm: cannot remove `sample_output/DASToolRun1_proteins.faa.all.b6': No such file or directory
running DAS Tool with 30 threads
evaluating bin-sets
starting bin selection from  20  bins
||||||||||||||||
extracting bins to sample_output/DASToolRun1_DASTool_bins"**

My ruby_version is 2.3.3, and every requirements may be OK.

I don't know how to solve this problem, could you give me some suggestion?

I hope your reply!

Best regards

**Comment by cmks** [comment]
Hi,

Can you please check if you can execute usearch by just typing:
`usearch --version`
into your terminal?

If that does not work you have to create an alias called `usearch` that points to your usearch9.2.64_i86linux32 executable like:
`ln -s /usr/local/bin/usearch9.2.64_i86linux32 /usr/local/bin/usearch`

If you don't have the permission to do that you can also create the alias in your home directory and add it to your PATH like:
`ln -s /usr/local/bin/usearch9.2.64_i86linux32 ~/bin/usearch`
and add the following line to your .bash_profile:
`export PATH="~/bin:$PATH"`

Alternatively, you can also simply rename 'usearch9.2.64_i86linux32' if you have the necessary permissions:
`mv /usr/local/bin/usearch9.2.64_i86linux32 /usr/local/bin/usearch`

Let me know if this helps.

Best regards,
Christian

**Comment by zhangws119** [comment]
@cmks 

I'm so sorry for this late reply. I try to mv /usr/local/bin/usearch9.2.64_i86linux32 /usr/local/bin/usearch, 

it's perfectly solve this problem. But I find another problem with the script in /src/Fasta_to_Scaffolds2Bin.sh,

The DAS_Tool.sh cannot read the files.tsv what from this script. Because  it can only read scaffolds Id \t bins ID 

not support  Bins_ID \n   
                     scaffolds_ID \t Bins_ID\n

Could you Modify the script ?

Many many thanks for your help!

Best regards

**Comment by cmks** [comment]
Hi,
Can you please send me your commands of Fasta_to_Scaffolds2Bin.sh and DAS_Tool.sh as well as the error message that you get? Also please send me the output of Fasta_to_Scaffolds2Bin.sh. If you can't send it here, please send it via mail to csieber@lbl.gov.
Regards,
Christian
