### ISSUE TITLE
the issue about install

### ISSUE THREAD

**Issue by qiaoxuejiao** [cmks/DAS_Tool#31]
Hi,
I can not install DAS_tool correctly. I decompress the DASTool_1.1.1.tar.gz and its content as followed:
![image](https://user-images.githubusercontent.com/30583482/48067588-98bf6d80-e20b-11e8-80cc-272753420e75.png)
I dont know what to do. Could you help me?

Shirley,
Thanks very much!

**Comment by SilasK** [comment]
Conda install -c bioconda das_tool

**Comment by cmks** [comment]
Using bioconda is probably the easiest way to install DAS Tool at the moment. 

If you prefer the manual way, you either have to clone the repo:
```
git clone https://github.com/cmks/DAS_Tool.git
```
or download the latest release:
```
wget https://github.com/cmks/DAS_Tool/archive/1.1.1.zip
unizp 1.1.1.zip
```
After that you have to install the DAS Tool R-package. This is the archive you were looking at, which  is inside the DAS Tool folder:
```
cd DAS_Tool-1.1.1
R CMD INSTALL ./package/DASTool_1.1.1.tar.gz
```
