### ISSUE TITLE
the error about R

### ISSUE THREAD

**Issue by Shirley-Q** [cmks/DAS_Tool#33]
Hi,
It has an error all the time when I install R. I tried different versions, but it did not worked. Can you help me?
![screenshot from 2018-11-23 22-22-25](https://user-images.githubusercontent.com/30583482/48948657-376bfe00-ef70-11e8-9f53-ffcf97f06ed4.png)

Best wishes,
Shirley

**Comment by SilasK** [comment]
Have you tried to install the package via conda?  

Have you specified the version for data.table ? if yey what happens if you use the most up to data one. 


By the way: If you copy your error message it becomes searchable.

**Comment by Shirley-Q** [comment]
I install R using a command 'apt-get install r-base-core'. Now my R is 3.4.4
I did not specify the version for data.table.
I copy my error message but it are not solved.

**Comment by Shirley-Q** [comment]
If i have conda,i donot need install R,right?
I have conda and I can not install das_tool using conda. Because it also have error.
/home/yuke/Desktop/Screenshot from 2018-11-23 23-30-34.png

**Comment by SilasK** [comment]
you pasted only the path to an image, this doesn't help me, sorry.

**Comment by Shirley-Q** [comment]
Oh, I am so sorry.
![screenshot from 2018-11-26 15-29-42](https://user-images.githubusercontent.com/30583482/48999001-3dd8c080-f190-11e8-86aa-d162e6c25d77.png)

**Comment by SilasK** [comment]
Haha, conflicting dependencies. Now comes the usefulness of conda: Create a environment for das tool. 
```
conda create -n dastoolenv -c bioconda das_tool
```
otherwise you can also deinstall futures.
What are you trying to do?

**Comment by Shirley-Q** [comment]
Thank you very much! I installed it successfully! Now it does not have the folder of das_tool_1.1.1 when I  installed it with conda. What should I do on the step 'Preparation of input files'? I have an error as followed.
![input](https://user-images.githubusercontent.com/30583482/49005529-e3e0f680-f1a1-11e8-9236-693d82ffdf55.png)

**Comment by SilasK** [comment]
Apparently, you don’t have the executable `/bin/env` This should be installed on all linux systems!

Search google `/bin/env bad interpreter` and re-install it. 

As a hack you can also change the first line of the Fasta_to_Scaffolds2Bin.sh script to `#!/bin/bash`

But the error is likely to re-appear.

**Comment by Shirley-Q** [comment]
I change the first line of the Fasta_to_Scaffolds2Bin.sh script to `#!/bin/bash` and it worked. But I have new error. I add a symbolic link called usearch with 'ln -s usearch9.0.2132_i86linux32 usearch', But it did not work.
![usearch](https://user-images.githubusercontent.com/30583482/49014778-30393000-f1bc-11e8-81f9-3436e15eb3ef.png)

**Comment by SilasK** [comment]
Explication:
the  `DAS_Tool` script is somewhere in `anaconda/envs/dastoolenv/bin`

1. Add usearch to your path! 
`export PATH="/path/to/usearch:$PATH" `

**Comment by Shirley-Q** [comment]
But I don't have usearch. So I dont know how to write /path/to/usearch
![u](https://user-images.githubusercontent.com/30583482/49021809-71d2d680-f1ce-11e8-89e6-66ced0c1aed7.png)

**Comment by SilasK** [comment]
use diamond: 
DAS_Tool --search_engine diamond

**Comment by Shirley-Q** [comment]
![image](https://user-images.githubusercontent.com/30583482/49022157-2cfb6f80-f1cf-11e8-99ab-4e6ecde42f9b.png)

**Comment by SilasK** [comment]
@cmks It seems there is some bug in the code on line 241.

@Shirley-Q 

`DAS_Tool --search_engine diamond -i sample_data.... -l maxbin,metabat -c ... -o . `


what is the output of the folowing:

```
conda activate dastoolenv
cd  ~
usearch
```

**Comment by Shirley-Q** [comment]
Hi,
I download usearch in the official website and install it use command 'chmod +x usearch'. Now there is no error tips about usearch. There is new error tip.
![93](https://user-images.githubusercontent.com/30583482/49093645-79ae7b80-f29f-11e8-9780-abda347fcb21.png)

**Comment by SilasK** [comment]
I think the output folder hast to exist. Creat it before running DAS_Tool

**Comment by cmks** [comment]
The output folder is now created automatically if it doesn't exist.
