### ISSUE TITLE
BSD split (macOS) does not support numeric suffixes

### ISSUE THREAD

**Issue by gaberoo** [cmks/DAS_Tool#36]
https://github.com/cmks/DAS_Tool/blob/53fd2ca25a6d16a4aeddc8b981e931626920c868/DAS_Tool#L340

Do you really need the numeric suffixes though? Lexicographical ordering should be fine too with `ls *`

https://github.com/cmks/DAS_Tool/blob/53fd2ca25a6d16a4aeddc8b981e931626920c868/DAS_Tool#L349

Also, macOS split does not use long options. However, I think the following will work both with BSD split and GNU split. DAS_Tool runs on the sample data, but I haven't extensively checked everything.

```
split -l ${lines_per_file} ${dastoolthreadstmpheader} $outputbasename\_dastoolthreadstmp.
```

**Comment by cmks** [comment]
The numeric suffixes are indeed not needed. Thanks for your input!
