### ISSUE TITLE
DAS_Tool now in Homebrew

### ISSUE THREAD

**Issue by gaberoo** [cmks/DAS_Tool#37]
Hi, 

Just FYI, we've added DAS_Tool to Homebrew's brewsci/bio repository. In case you want to update the installation info:

```
brew tap brewsci/bio
brew install das_tool
```
or
```
brew install brewsci/bio/das_tool
```

**Comment by cmks** [comment]
Thanks, that's awesome and very useful! 
I just tested the installation via Homebrew and it worked fine. However, I was facing a segmentation fault when loading the data.table r-package. Re-installation of the package solved the problem.

I have added your installation instructions to the readme.
