### ISSUE TITLE
No error if ruby isn't installed

### ISSUE THREAD

**Issue by seanmcallister** [cmks/DAS_Tool#4]
I was running DAStool on a server and didn't even think that the node I was trying to run it on didn't have ruby installed. DAStool ran prodigal fine, but the scg pipeline is a ruby script. When it got to it, it says it is predicting scg, but the only errors it gives is that the scg output doesn't exist when it tries to mv and rm. I think it would be helpful to have a check for ruby and a good error report on that one. I was trying to figure out why usearch wasn't working and didn't even think about ruby until I looked at the DAStool script. Thanks!

**Comment by cmks** [comment]
Thanks for running DAS Tool and for your feedback! I implemented a check and added meaningful error messages if ruby cannot be found on a system.

Best regards,
Christian
