### ISSUE TITLE
Missing check for required '-o, --outputbasename' parameter

### ISSUE THREAD

**Issue by ozcan** [cmks/DAS_Tool#41]
Hi,

When `-o` is not provided, there are no errors shown but the program fails later with a confusing message.  After tracing down, I realized that even though this parameter is not provided, bash script parsed and passed this parameter as an empty string to Rscript which caused all other command line arguments to shift indexes. 

Thank you,

**Comment by cmks** [comment]
Good catch, I'll have to write a fix for this case!
