### ISSUE TITLE
--db_directory

### ISSUE THREAD

**Issue by TealFurnholm** [cmks/DAS_Tool#43]
How can I add to/modify the default list of single-copy genes? I have a variety of environmental and human samples with fungal and other eukaryota, so need to adapt the list. What format do they need to be in (eg. header special character limitations? fasta or gbk or gff or tab?...etc)

**Comment by cmks** [comment]
Unfortunately, it's currently not possible to use custom sets of single copy genes without making changes to the code. However, it's on my list to add this feature to a future version of DAS Tool.

**Comment by cmks** [comment]
The [dev_customSCG](https://github.com/cmks/DAS_Tool/tree/dev_customSCG) branch of DAS Tool can make use of custom single copy gene sets. See also: #69.
