### ISSUE TITLE
ambiguous redirect

### ISSUE THREAD

**Issue by KunathBJ** [cmks/DAS_Tool#47]
Hello!

I've run Dastool from the conda installation and using the input from both metabat2 and maxbin2.
I've run it successfully without any error but also without the --write_unbinned option.

Now that I try to use it, Dastool runs, but I do receive an error and the unbinned are not transferred.
The command i use is
`DAS_Tool -i $P1/scaffolds2bin.tsv,$P2/scaffolds2bin.tsv -l metabat2,maxbin2 -c $P3/contigs500.fasta -o $P3/dastool_06_out/out --write_bin_evals 1 --create_plots 1 --write_bins 1 --write_unbinned 1 --score_threshold 0.6 -t 2`

And the error I receive is:
```
diamond v0.9.26.127 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

Running DAS Tool using 2 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using usearch v11.0.667_i86linux32
WARNING: non-unique bin-IDs found
        creating unique bin-IDs

evaluating bin-sets
starting bin selection from 245 bins
||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
bin selection complete: 60 bins above score threshold selected.
extracting bins to /scratch/users/bkunath/MUST_New/must_m_05/M5.2_Vall_Assembly/dastool_06_out/out_DASTool_bins
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
/home/users/bkunath/miniconda2/envs/dastool/bin/DAS_Tool: line 449: $bin_folder\/$bin\.ctgtmp: ambiguous redirect
```

Any input on what happened?? 
Thanks a lot for your help!

Ben

**Comment by cmks** [comment]
I fixed the problem. Pull the latest version and install the new r-package: 
```R CMD INSTALL package/DASTool_1.1.2.tar.gz```

**Comment by KunathBJ** [comment]
Hello!

Our server is down for maintenance this week but I will try ASAP next week and let you know how it went.

Thanks a lot!
Ben

**Comment by KunathBJ** [comment]
Hello,

Quick question: So far I've used Conda to install DasTool.
With this new package, what should I do? Use my previous installation and add the new R-package? Reinstall via conda? Or reinstall from source??
The easiest for me would be conda though ^^

Thanks a lot
Ben

**Comment by cmks** [comment]
I'm not sure how quickly changes propagate into the bioconda repo as it is managed externally. So if you want to try the changes right away, I recommend installing from source.

**Comment by KunathBJ** [comment]
Hello,

I actually kept my environment from conda (with all dependencies) and then just modified what I had to from your correction and it works just fine. Thanks a lot

Quick question though: When DASTool runs prodigal, does it predict full length/complete ORF or also incomplete ones? 

Thanks again!
Ben

**Comment by cmks** [comment]
Prodigal is reporting genes that run off edges but is prevented from making predictions that span "N"-containing stretches. The parameters are:
```
prodigal -a proteins.faa -i contigs.fa -p meta -m
```
