### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Niazevedo** [cmks/DAS_Tool#5]
Hi,

I was running Das_Tools and its terminated with the following error message:

rm: cannot remove 'dastoolthreadstmpheader': No such file or directory
/services/tools/das_tool/1.0/DAS_Tool.sh: line 260: sample_output/_proteins.faa: No such file or directory
rm: cannot remove 'dastoolthreadstmp.*': No such file or directory
mv: cannot stat 'sample_output/_proteins.faa.scg': No such file or directory
mv: cannot stat 'sample_output/_proteins.faa.scg': No such file or directory
rm: cannot remove 'sample_output/_proteins.faa.findSCG.b6': No such file or directory
rm: cannot remove 'sample_output/_proteins.faa.scg.candidates.faa': No such file or directory
rm: cannot remove 'sample_output/_proteins.faa.all.b6': No such file or directory
/services/tools/das_tool/1.0/DAS_Tool.sh: line 300: sample_output/.seqlength: No such file or directory
tr: write error: Broken pipe
tr: write error
sed: couldn't write 203187 items to stdout: Broken pipe
Execution halted

**Comment by cmks** [comment]
Hi,
Can you please send me the full command that you used for running DAS_Tool? Besides that, can you please check if you have write permissions for the directory that you specified as output ( -o/ --outputbasename options)?
Thanks,
Christian

**Comment by Niazevedo** [comment]
DAS_Tool.sh -i Coassembly1.tsv,
				Coassembly2.tsv,
				Sample1Mads.tsv,Sample3Mads.tsv,
				Sample6Mads.tsv,Sample7Mads.tsv,
				Sample1VizBin.tsv,Sample2VizBin.tsv,
				Sample3VizBin.tsv,Sample4VizBin.tsv,
				Sample5VizBin.tsv,Sample6VizBin.tsv,
				Sample7VizBin.tsv
			-l Coassembly1, Coassembly2, Sample1Mads, Sample3Mads, Sample6Mads, Sample7Mads, Sample1VizBin, Sample2VizBin, Sample3VizBin, Sample4VizBin, Sample5VizBin,
				Sample6VizBin,Sample7VizBin
			-c contig.fa
			-o output
			--threads 56

And I have write permissions

**Comment by cmks** [comment]
Hi,

I implemented a little bugfix which hopefully solves your problem. Please download the latest "DAS_Tool.sh" from the repository and copy it to your installation directory of DAS_Tool (replace the old DAS_Tool.sh in doing so).

If you run DAS_Tool again, please make sure not to include spaces in the comma separated lists of scaffold2bin-files (-i) and labels (-l).

Additionally, based on the name of your input files to me it looks like you're trying to combine predictions of different assemblies/samples. DAS_Tool works on binning predictions that were applied to the same assembly. Assuming you applied the binners "Mads" and "VizBin" to the assemblies of your Samples 1 to 7 the command for DAS_Tool for Sample1 would look like:

DAS_Tool.sh -i Sample1Mads.tsv,Sample1VizBin.tsv -l Mads,VizBin -c Sample1_contigs.fa -o Das_Tool_output_dir/Sample1

Thanks,
Christian

**Comment by Niazevedo** [comment]
Now some new errors appear:

/services/tools/das_tool/1.0/DAS_Tool.sh: line 250: sample_output/_dastoolthreadstmpheader: No such file or directory
-p destination: Broken pipe
grep: write error
/services/tools/das_tool/1.0/DAS_Tool.sh: line 252: sample_output/_dastoolthreadstmpheader: No such file or directory
split: 0: invalid number of lines
Try 'split --help' for more information.
rm: cannot remove 'sample_output/_dastoolthreadstmpheader': No such file or directory
/services/tools/das_tool/1.0/DAS_Tool.sh: line 259: sample_output/_dastoolthreadstmp.*_contigs.fa: No such file or directory
/services/tools/das_tool/1.0/DAS_Tool.sh: line 263: sample_output/_proteins.faa: No such file or directory
rm: cannot remove 'sample_output/_dastoolthreadstmp.*': No such file or directory
mv: cannot stat 'sample_output/_proteins.faa.scg': No such file or directory
mv: cannot stat 'sample_output/_proteins.faa.scg': No such file or directory
rm: cannot remove 'sample_output/_proteins.faa.findSCG.b6': No such file or directory
rm: cannot remove 'sample_output/_proteins.faa.scg.candidates.faa': No such file or directory
rm: cannot remove 'sample_output/_proteins.faa.all.b6': No such file or directory
/services/tools/das_tool/1.0/DAS_Tool.sh: line 303: sample_output/.seqlength: No such file or directory
tr: write error: Broken pipe
tr: write error
sed: couldn't write 203187 items to stdout: Broken pipe
Execution halted


I have removed the spaces in the comma separated lists and although the names use different samples, it's only different time samples with the same contents.

**Comment by cmks** [comment]
Hi Niazevedo,

It looks like there is a problem with perl on your system. What OS are you using? And what version of perl is installed (type: perl --version)?
For now, I replaced all perl one-liners with alternative statements. Can you please download DAS_Tool.sh again and give it a try?

Just to make sure that your file formats are ok, can you also please try to run DAS_Tool on the sample files which are in the installation directory? The sample commands are displayed if you run: DAS_Tool.sh -h

Thanks,
Christian
