### ISSUE TITLE
DASTool Snakemake error

### ISSUE THREAD

**Issue by susheelbhanu** [cmks/DAS_Tool#50]
Hi all, 
I'm running DASTool via snakemake, and for some reason, though I get the output bins, the following error crops us. While it's a minor annoyance since I have the output, it kills my snakemake run immediately after. The snakefile looks like this:
```
rule DAS_Tool:
    input:
            da1="{datadir}/{mapper}_{reads}_{sample}/dastool_output/{sample}_metabat.scaffolds2bin.tsv",
            da2="{datadir}/{mapper}_{reads}_{sample}/dastool_output/{sample}_maxbin.scaffolds2bin.tsv",
            da3="{datadir}/{sample}.fna",
            db=config["dastool_database"]
    threads:config["threads"]
    conda:"binning.yml"
    output:
            daout=directory("{datadir}/{mapper}_{reads}_{sample}/dastool_output/{sample}")
    shell:
            """
            date
            DAS_Tool -i {input.da1},{input.da2} -c {input.da3} -o {output.daout} --search_engine diamond -l maxbin2,metabat2 --write_bins 1 --write_bin_evals 1 --threads {threads} --db_directory {input.db} --create_plots 1 &&\
            2> >(tee {log}.stderr) > >(tee {log}.stdout)
            touch das_tool.done
            date
```

The error reads as such: 
```
usearch: command not found
Waiting at most 120 seconds for missing files.
MissingOutputException in line 277 of /mnt/lscratch/users/sbusi/ONT/cedric_ont_basecalling/Binning/metaspades_binning_snakefile:
Job completed successfully, but some output files are missing. Missing files after 120 seconds:
/scratch/users/sbusi/ONT/cedric_ont_basecalling/Binning/bwa_sr_metaspades/dastool_output/metaspades
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

Any ideas why it's looking for **usearch** despite the DIAMOND specification? Also what other files may be missing that it's terminating the job? I've tried the --latency-wait option upto 900 seconds, but no luck yet. 

Thank you!

**Comment by cmks** [comment]
Hi susheelbhanu,
Can you make sure that you're using the latest version of DAS Tool? The problem might already have been fixed in v1.1.2.

Although DAS Tool is checking dependencies before running, usearch is only tested and executed if you don't specify anything else as search tool. Are there any messages about usearch missing if you're running DAS Tool without snakemake from the command line? 
A hack/workaround could be to create an executable dummy-file with the name 'usearch' in your path. Snakemake is probably only checking if the file is there and might proceed without an error.

**Comment by susheelbhanu** [comment]
Thank you. I managed to download usearch, and give it the path, though still using diamond to run the search. 

On a related note, is there a way to ask DASTool to continue running despite one of the scaffolds2bin file being empty? I'm running it as a pipeline, and for one of the samples, the metabat bins are below the coverage levels. So the whole pipeline fails. I don't think there is such as option, but just wanted to confirm. 

Thanks again for your help!

**Comment by cmks** [comment]
Closing this ticket. See #67 for handling of empty scaffolds2bin input files.
