### ISSUE TITLE
Single copy gene prediction using diamond failed. Aborting

### ISSUE THREAD

**Issue by bhimbbiswa** [cmks/DAS_Tool#58]
Hi.

I am doing metagenomic analysis in Atlas (https://github.com/metagenome-atlas/atlas) pipeline.

I am getting this error again and again. Please help to solve.
```
DAS Tool run on  Wed Dec 9 10:47:40 JST 2020

User environment details:
Rscript path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/Rscript
Rscript version:  R scripting front-end version 4.0.3 (2020-10-10)
pullseq path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/pullseq
pullseq version:  Version: 1.0.2 Name lookup method: UTHASH
prodigal path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/prodigal
prodigal version:  Prodigal V2.6.3: February, 2016
ruby path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/ruby
ruby version: 
diamond path:  /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/bin/diamond
diamond version:  diamond version 2.0.5

Running DAS Tool using 1 thread.
identifying single copy genes using diamond version 2.0.5

single copy gene prediction using diamond failed. Aborting
```
I tried increasing the ram as well as changing the number of threads but same problem.

It stops with a core dump.
[core.25573.txt](https://github.com/cmks/DAS_Tool/files/5666511/core.25573.txt)

Please find the required logs attached.
[DASTool.log](https://github.com/cmks/DAS_Tool/files/5666488/DASTool.log)
[Main_log.txt](https://github.com/cmks/DAS_Tool/files/5666489/Main_log.txt)
[S13_DASTool.log](https://github.com/cmks/DAS_Tool/files/5666490/S13_DASTool.log)

**Comment by cmks** [comment]
Can you check if ruby is installed on your system? According to your log file, an executable with the name 'ruby' seems to exist but it's interesting that it does not return the version information. Try to run:
```
ruby --version
```
The output should be something like:
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

**Comment by bhimbbiswa** [comment]
Hi. 

Thank you very much for your reply.

It shows 
```
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

```
I again updated ATLAS and again ran the analysis. But same error. Please find the logs attached below.
[DASTool.log](https://github.com/cmks/DAS_Tool/files/5728217/DASTool.log)
[S13_DASTool.log](https://github.com/cmks/DAS_Tool/files/5728218/S13_DASTool.log)
[Atlas_all.sh.e11245365.txt](https://github.com/cmks/DAS_Tool/files/5728219/Atlas_all.sh.e11245365.txt)

As ATLAS create its own conda environment, please find a copy of JSON file attached about Ruby.

[Ruby_JSON_copy.txt](https://github.com/cmks/DAS_Tool/files/5728215/Ruby_JSON_copy.txt)

I think this problem is similar to #5  #11 and #13 as I got similar output in(see DASTool log)

I dearly wanted to use DASTool my analysis. Can you please help me.

Regards,

Bhim

**Comment by cmks** [comment]
Hi Bhim,

Thanks for your log files and environment information. Your ruby looks fine to me. Can run the single copy gene prediction script directly using the  following command and see if there are any error messages (you may have to adjust some paths)? 
```
./DAS_Tool/src/scg_blank_diamond.rb diamond S13/annotation/predicted_genes/S13.faa DAS_Tool/db/bac.all.faa DAS_Tool/db/bac.scg.faa DAS_Tool/db/bac.scg.lookup 1
```

While running some tests, I've  noticed that diamond has an issue with writing temporary files when the database is located on a mounted volume. I'm not sure if that's the problem in your case. However, the error message looks like this:
```
Searching alignments... Device not configured
Device not configured
Error: Error writing file diamond-tmp-2RAS0b Error: Error writing file diamond-tmp-nH2nTe

libc++abi.dylib: terminating with uncaught exception of type File_write_exception: Error writing file diamond-tmp-nH2nTe
libc++abi.dylib: terminating with uncaught exception of type File_write_exception: Error writing file diamond-tmp-2RAS0b
```

Cheers,
Chris

**Comment by bhimbbiswa** [comment]
Hi.

I am really sorry for my very late reply. Was stuck in some other work.

I used the following command but again core dump happened.

```
/lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/share/das_tool-1.1.2-1/src/scg_blank_diamond.rb diamond /lustre7/home/bhimbiswa/New_micro/S13/annotation/predicted_genes/S13.faa /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/share/das_tool-1.1.2-1/db/bac.all.faa /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/share/das_tool-1.1.2-1/db/bac.scg.faa /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/share/das_tool-1.1.2-1/db/bac.scg.lookup 1

```
This is the output I got 
```
/var/spool/uge/m06/job_scripts/11282269: line 8: 63698 Segmentation fault      (core dumped) /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/share/das_tool-1.1.2-1/src/scg_blank_diamond.rb diamond /lustre7/home/bhimbiswa/New_micro/S13/annotation/predicted_genes/S13.faa /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/share/das_tool-1.1.2-1/db/bac.all.faa /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/share/das_tool-1.1.2-1/db/bac.scg.faa /lustre7/home/bhimbiswa/New_micro/databases/conda_envs/92a32d4b/share/das_tool-1.1.2-1/db/bac.scg.lookup 1
```

[DAStool.sh.txt](https://github.com/cmks/DAS_Tool/files/5863723/DAStool.sh.txt)

Reagrds,

Bhim

**Comment by nuriaher** [comment]
Hi,

I don't know if this has been already said, but the Atlas pipeline you are mentioning is apparently implemented in Snakemake, also, I have been running DASTool from Snakemake for the past year and everything was fine until the end of December 2020. By then, when I try to run DASTool from Snakemake I get the same error as Bhim:
```
/services/tools/das_tool/1.1.2/DAS_Tool: line 407: 38191 Segmentation fault      (core dumped) ruby $DIR\/src/scg_blank_$search_engine\.rb $search_engine $proteins $db_dir\/bac.all.faa $db_dir\/bac.scg.faa $db_dir\/bac.scg.lookup $threads > /dev/null 2>&1
mv: cannot stat ‘/home/projects/ku-cbd/people/nurher/coassembly_test_BATS/MCB_04-BinMerging/GroupC_proteins.faa.scg’: No such file or directory
/services/tools/das_tool/1.1.2/DAS_Tool: line 407: 38193 Segmentation fault      (core dumped) ruby $DIR\/src/scg_blank_$search_engine\.rb $search_engine $proteins $db_dir\/arc.all.faa $db_dir\/arc.scg.faa $db_dir\/arc.scg.lookup $threads > /dev/null 2>&1
```

and when I run DASTool from Python or directly on the command line no issues are observed.
The ruby version I use is ruby/2.6.3. 


Regards,
Núria

**Comment by bhimbbiswa** [comment]
As suggested by @yanhui09  in #13, removing Ruby from my conda environment solved the problem.

As suggested, I used the following command in the conda environment in which this program was running.
```
conda remove ruby --force
```
Closing this issue as the problem is solved.
