### ISSUE TITLE
Waring: grep options are deprecated

### ISSUE THREAD

**Issue by SilasK** [cmks/DAS_Tool#59]
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script

Could you please correct this, in order that DAS Tool stays useable?  Thank you.

**Comment by cmks** [comment]
This warning is most likely connected to settings in your environment. Check these threads for possible solutions:
 - https://bbs.archlinux.org/viewtopic.php?id=190262
 - https://stackoverflow.com/questions/31156517/how-to-get-rid-of-grep-warning-grep-options-is-deprecated-please-use-an-alia

Let me know if any of the proposed solutions work for you.
