### ISSUE TITLE
SOME TROUBLES

### ISSUE THREAD

**Issue by zhenhaoluo** [cmks/DAS_Tool#6]
Hello, 
      When I am running DAS_TOOL. I have met some troubles. First, it tells me that "cannot stat '_proteins.faa.scg': No such file or directory". But I have installed diamond and Prodigal. Aren't these getting the  proteins seqs and single copy genes; second, I couldn't install Concoct, so I have just Metabat, MaxBin2,and ESOM. I have installed abawaca,too. But I don't know how to use abawaca. Could you please help me?
Thanks!

**Comment by zhenhaoluo** [comment]
my commandline is nohup ./DAS_Tool.sh -i /data/luozhh/project/FK.AMD.sediment/4.spades.out/metabatbin/metabat.result,/data/luozhh/project/FK.AMD.sediment/4.spades.out/maxbin2.result -l maxbin,metabat -c /data/luozhh/project/FK.AMD.sediment/4.spades.out/scaffolds.fasta --proteins luozhh_DAS_out/scaffolds.pro.fa -o luozhh_DAS_out/DAS_result  --search_engine diamond &

**Comment by zhenhaoluo** [comment]
my commandline is nohup ./DAS_Tool.sh -i /data/luozhh/project1/metabatbin/metabat.result,/data/luozhh/project1/maxbin/maxbin2.result -l maxbin,metabat -c /data/luozhh/project1/scaffolds.fasta --proteins /data/luozhh/project1/scaffolds.pro.fa -o luozhh_DAS_out/DAS_RUN --search_engine diamond &

**Comment by zhenhaoluo** [comment]
The abawaca-build command is abawaca-build -f <fasta-file> -o <out-directory> -s <sam-files-glob> -c <source-sam-file>
abawaca -u <abawaca-build-directory> -f <fasta-file> -o <out-dir> [-p <# CPUs>] [-c <gene2scg>]

**Comment by zhenhaoluo** [comment]
abawaca-build -f <fasta-file> -o <out-directory> -s <sam-files-glob> -c <source-sam-file>
abawaca -u <abawaca-build-directory> -f <fasta-file> -o <out-dir> [-p <# CPUs>] [-c <gene2scg>]

**Comment by zhenhaoluo** [comment]
And the abawaca troubles is  
The abawaca build usage is
abawaca-build -f fasta-file -o out-directory -s sam-files-glob -c source-sam-file
I think -s is for the raw data mapping to the scaffolds and get the sam-file, but I don't know what the -s is for?
and the abawaca usage is
abawaca -u <abawaca-build-directory> -f <fasta-file> -o <out-dir> [-p <# CPUs>] [-c <gene2scg>]
-p I think is the threads number but I don't know what the -c is for. 
Could you please help me?
Thank you

**Comment by cmks** [comment]
Hi zhenhaoluo,

Thanks for your feedback on DAS Tool! Your command looks fine to me. However, there might be a problem in the formatting of your protein fasta file. Can you try to run DAS Tool again but remove the `--proteins /data/luozhh/project1/scaffolds.pro.fa` option? This way DAS Tool will run prodigal to predict genes and generate a compatible protein fasta file.

In ABAWACA, the -c option is for the mapping of reads that were used to create the assembly (reads from the same sample). The option -s is a legal glob pattern that covers all sam files of mappings from other samples to the assembly (crossmapping for differential abundance information). E.g: 
`abawaca-build -f sample01.fasta -o abawaca_sample01 -s mapping_sample01_sample*.sam -c mapping_sample01_sample01.sam`
 if you run 
`ls mapping_sample01_sample*.sam`
you should see a list of sam files like:
`mapping_sample01_sample01.sam mapping_sample01_sample02.sam mapping_sample01_sample03.sam`

For other questions to ABAWACA, please check out the github page of Itai Sharon: https://github.com/CK7/abawaca

Thanks,
Christian

**Comment by zhenhaoluo** [comment]
Hi Christian,
Thank you for so much for answering my question. I have try to run the DAS Tool  as you said, but the troubles still exist. It said, "predicting genes using prodigal
identifying single copy genes using diamond
mv: cannot stat 'luozhh_DAS_out/DASTOOLRUN1_proteins.faa.scg' : No such file or directory
mv: cannot stat ‘luozhh_DAS_out/DASTOOLRUN1_proteins.faa.scg’: No such file or directory
rm: cannot remove ‘luozhh_DAS_out/DASTOOLRUN1_proteins.faa.findSCG.b6’: No such file or directory
rm: cannot remove ‘luozhh_DAS_out/DASTOOLRUN1_proteins.faa.scg.candidates.faa’: No such file or directory
rm: cannot remove ‘luozhh_DAS_out/DASTOOLRUN1_proteins.faa.all.b6’: No such file or directory
running DAS Tool with 30 threads
Execution halted"
What's more, I have tried to try the sample data as commended, and it said:
"predicting genes using prodigal
identifying single copy genes using diamond
mv: cannot stat ‘sample_output/DASTOOlrun3_proteins.faa.scg’: No such file or directory
mv: cannot stat ‘sample_output/DASTOOlrun3_proteins.faa.scg’: No such file or directory
rm: cannot remove ‘sample_output/DASTOOlrun3_proteins.faa.findSCG.b6’: No such file or directory
rm: cannot remove ‘sample_output/DASTOOlrun3_proteins.faa.scg.candidates.faa’: No such file or directory
rm: cannot remove ‘sample_output/DASTOOlrun3_proteins.faa.all.b6’: No such file or directory
running DAS Tool with 30 threads
Execution halted"
Additonally, if I have three sample, how can I run the abawaca?
Thank,
Luozhh

**Comment by zhenhaoluo** [comment]
Hi, Christian,
The second question is means that, if I have three sample, how could I get the mapping_sample01_sample02.sam and mapping_sample01_sample03.sam. Is that mapping the sample2.rawdata to the AllsampleAssembly.fasta? Could you please tell me more details? I have also check out https://github.com/CK7/abawaca, and left some questions on his page, but maybe he's so busy that he haven't read my email.
Thanks,
Luozhh

**Comment by zhenhaoluo** [comment]
Hi, Christian,
I think that maybe the db is in the wrong place. So should I place the the file named db in the main dir of the DAS_TOOLs or in the input_data_file?

**Comment by zhenhaoluo** [comment]
Hi, Christian,
Maybe I think I find where the problems is. In my lab, most people still use diamond (diamond v0.7.9.58) and I cannot change the version. I could just install the software in my own profile. So could you tell me how to change the shell scripts to let it know to run diamond in my own profile? 
Thanks,
Luozhh

**Comment by zhenhaoluo** [comment]
Hi Christian,
Thanks for answering the question. However, I still don't know any about abawaca, So could you tell me if I have three sample, how could I run the abawaca?
Secondly, I think that I find where the problem is , the ruby version in my lab is not suitable for the DAS_TOOLs. So I think it's better to run the ruby in my own file. But I don't know how to tell the DAS_TOOL to run the ruby that I installed. Looking forward to hearing from you.
Thanks,
Luozhh

**Comment by cmks** [comment]
Hi Luozhh,

Which version of ruby is your lab using? And why do you think it's not suitable? If you prefer to use your own ruby this page shows some ways to switch between versions: https://makandracards.com/makandra/21545-rbenv-how-to-switch-to-another-ruby-version-temporarily-per-project-or-globally

To your previous questions: 
If you want to use your own version of DIAMOND, simply add the installation path in front of your PATH like this:
`export PATH="/path/to/diamond_folder:$PATH"`
or initialize the DASTOOL_DIAMOND variable:
`DASTOOL_DIAMOND="/path/to/diamond_folder"`.

The db folder, you get after extracting "db.zip" has to go into the DAS_Tool installation directory. The folder is necessary for predicting single copy genes using DIAMOND.

If you want to run ABAWACA with three samples, all three mappings should be in one folder so that you can create a glob pattern that matches your sam files. For example if you have the three sam files named `mapping_sample01_sample01.sam mapping_sample01_sample02.sam mapping_sample01_sample03.sam`, then your glob pattern would be: mapping_sample01_**sample***.sam. You can test your pattern if you cd in your sam file directory and type `ls mapping_sample01_sample*.sam`. This should list your three sam files. The pattern is the input for the -s option:
abawaca-build -f sample01.fasta -o abawaca_sample01 **-s mapping_sample01_sample\*.sam** -c mapping_sample01_sample01.sam 

Thanks,
Christian

**Comment by zhenhaoluo** [comment]
Hi Christian,
It 's so nice of you! With your kindly help, I have managed to run the DAS_TOOLs. But I still cannot get the abawaca result. When I run the abawaca-build, it didn't predict the scg successfully, the stderr said 'sh: /Users/ItaiSharon/dropbox/software/bin/scg.pl: No such file or directory'. So could you please help me to solve the problem? Thank you so much!
Yours,
Luozhh

**Comment by cmks** [comment]
Hi Luozhh,
It seems like the path for the scg.pl script in ABAWACA is wrong as it links to Itai's Dropbox. Also scg.pl is not part of the repository. So you can't just fix the path. You should write Itai Sharon and ask him to fix the path and upload the missing script. There's not much I can do from my end.
Thanks,
Christian

**Comment by zhenhaoluo** [comment]
Hi Christian,
Thank you so much for helping me a lot. It's so nice of you. I will write to Ital Sharon and hope that it can be solved. 
Thanks,
Luozhh
