### ISSUE TITLE
Is it a good practice to combine bins generated from different search engines? 

### ISSUE THREAD

**Issue by Rui-Zzhang** [cmks/DAS_Tool#64]
Dear DASTool developers, 

I ran DASTool on bins from Metabat2, MaxBin2, and Concoct. It seems that the bins output by DASTool vary when I indicate different search engines (i.e. blast, diamond and usearch) for single-copy gene identification. I thought this could be a good way to produce more filtered bins, but I wonder if it's recommended to do so? (i.e. combines bins produced by searching from different search engines.) Thank you!

**Comment by cmks** [comment]
Hi @Rui-Zzhang,
I don't recommend doing that. However, it may make sense to stick to the search tool that delivers the best results for your data.

**Comment by Rui-Zzhang** [comment]
Hi @cmks, thanks for your advice!
