### ISSUE TITLE
Implement vsearch as another search_engine

### ISSUE THREAD

**Issue by jolespin** [cmks/DAS_Tool#68]
Since [vsearch](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5075697/) is free and easy to [install via conda](https://anaconda.org/bioconda/vsearch) (compared to usearch), would it be possible to include this option in future versions?

**Comment by cmks** [comment]
Yes, vsearch looks like a great and promising open-source alternative to the usearch. However, it still doesn't seem to support amino acid sequence alignments, which would be necessary for integrating it as a search engine.
