### ISSUE TITLE
Issue with the --threads option

### ISSUE THREAD

**Issue by adityabandla** [cmks/DAS_Tool#7]
DAS_Tool just refuses to run if the --threads option is specified. It just seems to ignore the entire command line and runs as if just DAS_Tool.sh was called without any options

Doesn't even throw an error, just exits

**Comment by cmks** [comment]
Hi adityabandla,

Thanks for using DAS Tool! Can you please send me the full command (with the --threads option) that is not working for you?

Cheers,
Christian

**Comment by adityabandla** [comment]
Hi Christian

Apologies for the late reply. This seems to happen only when the threads option is specified as the last argument. I got it to work, when I placed it in the middle

Regards
Aditya
