### ISSUE TITLE
Execution halted

### ISSUE THREAD

**Issue by iquasere** [cmks/DAS_Tool#70]
Installed DAS_Tool through Bioconda. Running ```DAS_Tool -c snakemake_learn/Assembly/Sample/contigs.fasta -o test_dastool/das_output --search_engine diamond --write_bins 1 --write_unbinned 1 -t 14``` gives me
```
Running DAS Tool using 14 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 2.0.9
calculating contig lengths.
Execution halted
```
Running with ```--debug``` option ends with
```
Computing hash join...  [0.027s]
Building seed filter...  [0.002s]
Searching alignments...  [0.004s]
Deallocating buffers...  [0.012s]
Clearing query masking...  [0s]
Computing alignments...  [0.141s]
Deallocating reference...  [0.007s]
Loading reference sequences...  [0s]
Deallocating buffers...  [0s]
Deallocating queries...  [0s]
Loading query sequences...  [0s]
Closing the input file...  [0s]
Closing the output file...  [0s]
Closing the database file...  [0.006s]
Deallocating taxonomy...  [0s]
Total time = 3.008s
Reported 299 pairwise alignments, 299 HSPs.
299 queries aligned.
The host system is detected to have 135 GB of RAM. It is recommended to increase the block size for better performance using these parameters : -b5 -c1
starting annotations of single copy cogs...
successfully finished
calculating contig lengths.
Execution halted
```
No idea what to do here, have already checked that all dependencies are reachable, including ```usearch```. This error is reproduced with the data available at ```sample_data```

**Comment by cmks** [comment]
Hi João,
Sorry to hear that you're having trouble running DAS Tool. If the error also shows up when running the example in the README on the `sample_data`, there is most likely an issue with your installation or your environment. Please make sure that you've also installed all required R-packages. You can also check the log file (when running in --debug mode) to get more information about the error.
Also, I've just recently fixed some bugs. Try cloning the latest code from the repository and also install the latest version of the DAS Tool R-package.

**Comment by iquasere** [comment]
Nice, this next version works like a charm. Thank you! ^^
