### ISSUE TITLE
doMC not found even if it's installed

### ISSUE THREAD

**Issue by SilasK** [cmks/DAS_Tool#75]
We get the folowing error https://github.com/metagenome-atlas/atlas/issues/496

```
Cleaning up...  [0s]
Total time = 4.138s
Reported 68 pairwise alignments, 68 HSPs.
68 queries aligned.
starting annotations of single copy cogs...
successfully finished
calculating contig lengths.
Error in library(x, character.only = TRUE) : 
  there is no package called ‘doMC’
Calls: lapply ... suppressPackageStartupMessages -> withCallingHandlers -> library
Execution halted
mv: cannot stat ‘sample2/binning/DASTool/sample2_DASTool_scaffolds2bin.txt’: No such file or directory
```

There is a problem with doMC even though it's installed with conda. Is a specific version required?

**Comment by cmks** [comment]
I've only tested doMC versions >= 1.3.4. However, the error message says that the package is not found - independently of the installed version. Have you checked if the R library path is set correctly?

**Comment by cmks** [comment]
Closing this ticket as the latest version ([1.1.4](https://github.com/cmks/DAS_Tool/releases/tag/1.1.4)) does not require doMC any more.
