### ISSUE TITLE
Execution Halted 'cherrypick aggregation' error 

### ISSUE THREAD

**Issue by jfy133** [cmks/DAS_Tool#77]
Hello,

I'm currently in the process of trying to integrate DAS_Tool (v1.1.3) into [nf-core/mag](https://github.com/nf-core/mag/).

When I run with the test data (fake 'metagenomic' data of a single bacterial genome), I hit the following error:

```
Running DAS Tool using 2 threads.
predicting genes using Prodigal V2.6.3: February, 2016
identifying single copy genes using diamond version 2.0.11
calculating contig lengths.
WARNING: Duplicated scaffolds in: SPAdes-MaxBin2-test_minigut_sample2.tsv 
Execution halted
```
Running with `--debug` gives the ends with:

```
successfully finished
calculating contig lengths.
WARNING: Duplicated scaffolds in: SPAdes-MaxBin2-test_minigut_sample2.tsv 
Error in aggregate.data.frame(arc_scg["count"], by = arc_scg[c("Archaeal.SCG",  : 
  no rows to aggregate
Calls: cherry_pick -> aggregate -> aggregate.data.frame
Execution halted
```

Do you have any suggestions how I could resolve the issue? Inferring from the error, are you _required_ to have archaeal genomes in your metagenome?

Data and the command used is attached here:
[dastool_error.zip](https://github.com/cmks/DAS_Tool/files/8205917/dastool_error.zip)

**Comment by jfy133** [comment]
I get different error with 1.1.4 (just saw it was released, I will investigate further first and reopen if necessary)

**Comment by jolespin** [comment]
@jfy133 Did you end up figuring this out? I'm only getting it for one of my samples.

**Comment by jfy133** [comment]
Hi @jolespin i was actually tackling this yesterday. Im a little test I found i didn't get the error with the latest version (1.1.4), however when I went to test it more thoroughly, I found the bioconda recipe was partly broken so I went back to fix it. That was merged yday afternoon....

So try 1.1.4, I guess, and otherwise I'll report back here if I still have the problem.
