### ISSUE TITLE
Scoring Function

### ISSUE THREAD

**Issue by adityabandla** [cmks/DAS_Tool#8]
Hi Christian

What are the default weighing parameters (b and c in the scoring function) used in DAS Tool? Is there a way to modify it?

Further, it might be great to have a simpler mapping of completeness/contamination to the scoring function values. Although, I understand the logic behind how the scoring function is being implemented, it does not make for quick interpretations in terms of completeness/contamination, for example, if I want bins with greater than or equal to 50% completeness and less than 10% contamination, what should be my scoring threshold?

Regards
Aditya

**Comment by adityabandla** [comment]
Does anyone have any ideas?

**Comment by cmks** [comment]
Hi Aditya,

The default values for the weighting parameters are b=1.5 and c=1. Unfortunately, it's not possible to modify them at the moment. If you want to filter for bins with a specific completeness and contamination ratio, the easiest way to do it is to look into the `*_summary.txt` output file. It gives you some stats for each selected bin including the number of single copy genes. The columns bacRatio and arcRatio contain the ratio of present bacterial and archaeal single copy genes per bin. It is safe to use the maximum of both as a completeness estimate. Unfortunately, there's no ratio for contamination but only the number of duplicated single copy genes. You'll have to divide the column multipleBacSCGs by 51 and multipleArcSCGs by 38 to get a contamination estimate. I'm going to add the ratio-column for duplicated SCGs in the next version of DAS Tool.

Alternatively you can run the software CheckM (https://ecogenomics.github.io/CheckM) on the output of DAS Tool to get an estimate for completeness and contamination.

Cheers,
Christian
