### ISSUE TITLE
Cound DAS_Tool re-combine the contig in different methods of bin to one high quality bin

### ISSUE THREAD

**Issue by neptuneyt** [cmks/DAS_Tool#80]
Dear DAS_Tool,
Thanks for your wonderful work.
I was wondering Suppose I get 2 sets of bins by 2 different binning methods, can DAS_Tool re-combine the bins of lower completeness in different methods into bins of higher completeness. For example
method_A_bin.1 has 20% completeness of species X and method_B_bin.3 has 60% completeness of species X. So does this software can combine method_A_bin.1 and method_B_bin.3 into a new genome with 80% completeness?
Thanks a lot.

**Comment by cmks** [comment]
No, DAS Tool is not combining bins to increase completeness.

**Comment by cmks** [comment]
Yes, it is similar to dRep but the use cases are different. DAS Tool combines binning predictions from the same assembly, whereas dRep dereplicates bins from different samples/assemblies.

Although the completeness of bins will not increase when running DAS Tool, it is possible that sequence redundancy (aka contamination) of bins can be removed.
