### ISSUE TITLE
Sample output errors & Execution halted error (Anvio)

### ISSUE THREAD

**Issue by ntseng57** [cmks/DAS_Tool#9]
Hi Christian,

I have two questions.

1) When I ran the sample data, I received this output in terminal: 

`DAS_Tool.sh -i sample_data/sample.human.gut_concoct_scaffolds2bin.tsv,sample_data/sample.human.gut_maxbin2_scaffolds2bin.tsv,sample_data/sample.human.gut_metabat_scaffolds2bin.tsv,sample_data/sample.human.gut_tetraESOM_scaffolds2bin.tsv -l concoct,maxbin,metabat,tetraESOM -c `

> sample_data/sample.human.gut_contigs.fa -o sample_output/DASToolRun1
> predicting genes using prodigal
> /Users/nancypro/Documents/Research/ELSI-USC/Research/MiSeq/DAS_Tool/DAS_Tool.sh: line 238: shuf: command not found
> split: illegal option -- -
> usage: split [-a sufflen] [-b byte_count] [-l line_count] [-p pattern]
>              [file [prefix]]
> pullseq - failed to open names file sample_output/DASToolRun1_dastoolthreadstmp.*
> identifying single copy genes using usearch
> mv: sample_output/DASToolRun1_proteins.faa.scg: No such file or directory
> mv: sample_output/DASToolRun1_proteins.faa.scg: No such file or directory
> rm: sample_output/DASToolRun1_proteins.faa.findSCG.b6: No such file or directory
> rm: sample_output/DASToolRun1_proteins.faa.scg.candidates.faa: No such file or directory
> rm: sample_output/DASToolRun1_proteins.faa.all.b6: No such file or directory
> running DAS Tool with 1 threads
> evaluating bin-sets
> starting bin selection from  20  bins
> ||||||||||||||||

I guess it's fine since the sample output folder contains these files with information in them and pdfs have completeness plotted:

> all_prot.udb
> DASToolRun1_concoct.eval
> DASToolRun1_DASTool_hqBins.pdf
> DASToolRun1_DASTool_scaffolds2bin.txt
> DASToolRun1_DASTool_scores.pdf
> DASToolRun1_DASTool_summary.txt
> DASToolRun1_maxbin.eval
> DASToolRun1_metabat.eval
> DASToolRun1_proteins.faa
> DASToolRun1_proteins.faa.archaea.scg
> DASToolRun1_proteins.faa.bacteria.scg
> DASToolRun1_proteins.faa.udb
> DASToolRun1_tetraESOM.eval
> DASToolRun1.seqlength
> DASToolRun2_DASTool_hqBins.pdf
> DASToolRun2_DASTool_scaffolds2bin.txt
> DASToolRun2_DASTool_scores.pdf
> DASToolRun2_DASTool_summary.txt
> DASToolRun2.seqlength

2) When I tried to use my own samples, I get the same errors as the sample data and also:

>  Execution halted 

I'm trying to connect Anvio's exported contigs database (with Anvio's default to split contigs longer than 20,000 bp; command to export: anvi-export-splits-and-coverages) with MetaBAT and MyCC binning. My pipeline after quality assessment and trimming was co-assembly using MegaHIT (I also have done separate assembly with MetaSPADES) --> Anvio metagenomic workflow --> MetaBAT and MyCC from Anvio's exported contigs database (I also did binning before Anvio's workflow but I haven't tried those bins with DAS_Tool yet). 

Here's few lines from tsv file I made for DAS_Tool from MetaBAT bins:

> c_000000127726_split_00001      M07.2
> c_000000126714_split_00001      M07.2
> c_000000126686_split_00001      M07.2

I also want to use DAS_Tool at some point to compare bins manually refined in Anvio's interactive, but the exported bin contig names lose the "_split_#####" (command to export bins: anvi-summarize).  

I thought this approach from Anvio to DAS_Tool might work because of a presentation at ASM, but I'm having some difficulty. Should I skip splitting in Anvio's workflow? or the bin names are not right (e.g. I should replace "M07" with "metabat")? or I should use the bins before Anvio workflow (which MetaSPADES outputs scaffolds)? 

Thank you!
Nancy

**Comment by ntseng57** [comment]
I figured out my problem. I had to install coreutils and add two paths to my .bash_profile. I suggest to also add this to the "dependency" list. 

`brew install coreutils`

> #put in .bash_profile or .bashrc
> export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
> export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

**Comment by cmks** [comment]
Hi Nancy,

Thank's for the hint! I didn't realize that the 'shuf' command is not part of a standard MacOS installation.
I will add the coreutils package to the list of dependencies.

Cheers,
Christian
