### ISSUE TITLE
Error: DAS Tool

### ISSUE THREAD

**Issue by wotohoku** [cmks/DAS_Tool#95]
I encounter an error with the DAS_Tool command. I use python 3.11.3.
Could someone let me know how to solve it?

The following is the executed command:

$ DAS_Tool -i metabat1.tsv,metabat2.tsv,maxbin2.tsv -c megahit_filter.fa -t 20 -o DAStool_dir/refine --write_bins 1 --create_plots 1 -l metabat1,metabat2,maxbin2 --search_engine blast

and it returns the following error:
Error: DAS Tool
Usage:
  DAS_Tool [options] -i <contig2bin> -c <contigs_fasta> -o <outputbasename>
  DAS_Tool -i <contig2bin> -c <contigs_fasta> -o <outputbasename> [--labels=<labels>] [--proteins=<proteins_fasta>] [--threads=<threads>] [--search_engine=<search_engine>] [--score_threshold=<score_threshold>] [--dbDirectory=<dbDirectory> ] [--megabin_penalty=<megabin_penalty>] [--duplicate_penalty=<duplicate_penalty>] [--write_bin_evals] [--write_bins] [--write_unbinned] [--resume] [--debug]
  DAS_Tool [--version]
  DAS_Tool [--help]

Options:
   -i --bins=<contig2bin>                   Comma separated list of tab separated contigs to bin tables.
   -c --contigs=<contigs>                   Contigs in fasta format.
   -o --outputbasename=<outputbasename>     Basename of output files.
   -l --labels=<labels>                     Comma separated list of binning prediction names.
   --search_engine=<search_engine>          Engine used for single copy gene identification (diamond/blastp/usear
Execution halted

**Comment by benjamingrodner** [comment]
I had the same error, it worked for me to remove the "1" after --write_bins and --write_bin_evals. Probably it's the same for --create_plots

**Comment by cmks** [comment]
Thanks @benjamingrodner. The 1/0 after `--write_bins`, `--write_unbinned`, `--write_bin_evals`,... is syntax from an old version.
